const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const FRONTEND = path.join(ROOT, "frontend");
const BACKEND = path.join(ROOT, "backend");
const DOCS = path.join(ROOT, "docs");

function read(relativePath) {
  return fs.readFileSync(path.join(ROOT, relativePath), "utf8");
}

function write(relativePath, content) {
  const target = path.join(ROOT, relativePath);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, content);
}

function copyFile(source, target) {
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.copyFileSync(source, target);
}

function cleanDocs() {
  if (fs.existsSync(DOCS)) fs.rmSync(DOCS, { recursive: true, force: true });
  fs.mkdirSync(DOCS, { recursive: true });
}

function buildStaticEngine() {
  const academic = read("backend/academic-framework.js")
    .replace(/module\.exports\s*=\s*\{[\s\S]*?\};\s*$/m, "");
  const resources = read("backend/social-resources.js")
    .replace(/module\.exports\s*=\s*\{[\s\S]*?\};\s*$/m, "");
  const inference = read("backend/case-inference.js")
    .replace('const { academicFramework, selectAcademicPrinciples } = require("./academic-framework");\r\n', "")
    .replace('const { academicFramework, selectAcademicPrinciples } = require("./academic-framework");\n', "")
    .replace('const { recommendResources } = require("./social-resources");\r\n', "")
    .replace('const { recommendResources } = require("./social-resources");\n', "")
    .replace(/module\.exports\s*=\s*\{[\s\S]*?\};\s*$/m, "");

  return `/* Generated by scripts/build-pages.js for GitHub Pages. */\n(() => {\n${academic}\n${resources}\n${inference}\nwindow.SOCIAL_STATIC_RESOURCES = socialResources;\nwindow.SOCIAL_STATIC_ENGINE = { generateStructuredReport, infer, validation, variableLabels };\n})();\n`;
}

function buildIndex() {
  return read("frontend/index.html")
    .replaceAll('href="/assets/', 'href="assets/')
    .replaceAll('src="/assets/', 'src="assets/')
    .replaceAll('href="/styles.css"', 'href="styles.css"')
    .replaceAll('src="/app.js"', 'src="app.js"')
    .replace('    <script src="app.js"></script>', '    <script src="static-engine.js"></script>\n    <script src="app.js"></script>');
}

cleanDocs();
write("docs/index.html", buildIndex());
write("docs/app.js", fs.readFileSync(path.join(FRONTEND, "app.js"), "utf8"));
write("docs/styles.css", fs.readFileSync(path.join(FRONTEND, "styles.css"), "utf8"));
write("docs/static-engine.js", buildStaticEngine());
write("docs/.nojekyll", "");

for (const file of fs.readdirSync(path.join(FRONTEND, "assets"))) {
  copyFile(path.join(FRONTEND, "assets", file), path.join(DOCS, "assets", file));
}

console.log("GitHub Pages build generated in docs/");
